DROP INDEX DS1;

CREATE INDEX DS2 ON EMPLOYEES (DEPARTMENT_ID, SALARY DESC);

TEST=# EXPLAIN (COSTS FALSE) SELECT NAME AS EMPLOYEE, SALARY FROM (

SELECT
    DEPARTMENT_ID,
    MAX(SALARY) AS SALARY
FROM
    EMPLOYEES
GROUP BY
    DEPARTMENT_ID ) AS E
    USING (DEPARTMENT_ID, SALARY);

QUERY PLAN
NESTED LOOP
-> GROUPAGGREGATE
GROUP KEY: EMPLOYEES.DEPARTMENT_ID
-> INDEX ONLY SCAN USING DS2 ON EMPLOYEES
-> INDEX SCAN USING DS2 ON EMPLOYEES E
INDEX COND: ((DEPARTMENT_ID = EMPLOYEE.DEPARTMENT_ID) AND (SALARY = (MAX(EMPLOYEES.SALARY))))

(6 СТРОК) TEST=# EXPLAIN (COSTS FALSE)
SELECT
    NAME AS EMPLOYEE,
    SALARY
FROM
    (
        SELECT
            NAME,
            SALARY,
            MAX(SALARY) OVER (PARTITON BY DEPARTMEN_ID) AS MS
        FROM
            EMPLOYEES
    ) AS E
WHERE
    SALARY=MS;

QUERY PLAN
SUBQUERY SCAN ON E
FILTER: (E.SALARY = E.MS)
-> WindowAgg 
-> INDEX SCAN USING DS2 ON EMPLOYEES

(4 СТРОКИ) TEST=# EXPLAIN (COSTS FALSE)
SELECT
    NAME AS EMPLOYEE,
    SALARY
FROM
    (
        SELECT
            NAME,
            SALARY,
            RANK() OVER (PARITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RNK
        FROM
            EMPLOYEES E
    ) AS E
WHERE
    RNK=1;

QUERY PLAN

Subquery Scan on e 
   Filter: (e.rnk = 1)
   ->  WindowAgg 
         Run Condition: (rank()  OVER (?) <= 1)
         -> Index Scan using ds2 on employees e_1
      